In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.losses import CategoricalCrossentropy

In [47]:
mnist = pd.read_csv("datasets/mnist.csv", header=None)
X = mnist.drop(0, axis=1).values
y = mnist[0].values
y = to_categorical(y)
print(mnist.shape)
mnist.head()

(2001, 785)

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
0,5,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.608,0.609,0.61,0.611,0.612,0.613,0.614,0.615,0.616,0.617
1,4,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2,3,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,0.000,0.000

In [51]:
# Create the model: model
model = Sequential()

# Add the first hidden layer
model.add(Dense(50, activation="relu", input_shape=(784,)))

# Add hidden layers
model.add(Dense(100, activation="relu"))
model.add(Dense(200, activation="relu"))
model.add(Dense(100, activation="relu"))

# Add the output layer
model.add(Dense(10, activation="softmax"))

# Compile the model
model.compile(optimizer="adam", loss=CategoricalCrossentropy(), metrics=["accuracy"])

# Fit the model
model.fit(X, y, validation_split=0.3, epochs=10, callbacks=[EarlyStopping(patience=2)])

Epoch 1/10
44/44 [==============================] - 1s 6ms/step - loss: 6.4684 - accuracy: 0.3921 - val_loss: 2.0813 - val_accuracy: 0.5574
Epoch 2/10
44/44 [==============================] - 0s 3ms/step - loss: 1.1996 - accuracy: 0.6943 - val_loss: 1.5916 - val_accuracy: 0.6190
Epoch 3/10
44/44 [==============================] - 0s 3ms/step - loss: 0.5904 - accuracy: 0.7993 - val_loss: 1.4308 - val_accuracy: 0.6705
Epoch 4/10
44/44 [==============================] - 0s 3ms/step - loss: 0.3744 - accuracy: 0.8779 - val_loss: 1.3894 - val_accuracy: 0.6988
Epoch 5/10
44/44 [==============================] - 0s 3ms/step - loss: 0.2452 - accuracy: 0.9136 - val_loss: 1.3223 - val_accuracy: 0.7138
Epoch 6/10
44/44 [==============================] - 0s 3ms/step - loss: 0.1416 - accuracy: 0.9514 - val_loss: 1.5474 - val_accuracy: 0.7255
Epoch 7/10
44/44 [==============================] - 0s 3ms/step - loss: 0.0921 - accuracy: 0.9707 - val_loss: 1.4741 - val_accuracy: 0.7537